apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: josephhoffman-josephhoffman-poi-map-app-dev
  annotations:
    argocd/app-name: josephhoffman-josephhoffman-poi-map-app-dev
    backstage.io/kubernetes-id: josephhoffman-josephhoffman-poi-map-app-dev
    backstage.io/kubernetes-namespace: josephhoffman
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=josephhoffman-josephhoffman-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/josephhoffman-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/josephhoffman/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/josephhoffman/deployments/josephhoffman-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/josephhoffman-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://josephhoffman-poi-map-app-josephhoffman.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "josephhoffman"
  system: workshop-system-josephhoffman
  consumesApis:
    - gateway-api-josephhoffman
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-josephhoffman
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "josephhoffman"
